### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by 740291272** [MeiK-h/QQMusicAPI#1]
Traceback (most recent call last):
  File "/Users/ghostgloomy/PycharmProjects/QQ音乐/QQMusic.py", line 97, in <module>
    song.music_save()
  File "/Users/ghostgloomy/PycharmProjects/QQ音乐/QQMusic.py", line 54, in music_save
    music_file = open(os.path.join(path, self.title + '.m4a'), 'wb')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 37: ordinal not in range(128)

**Comment by MeiK-h** [comment]
如果可以的话，最好使用 Python3 来运行此项目。
保存歌曲时默认存在 song 目录下，可以创建此目录或者指定一个其他的目录。
